/**
 * @file themePresets.local.js
 * @description Defines local theme presets and the active preset used by the app.
 */
export const THEME_PRESETS = {
    canyonSage: {
        primary: { main: "#8C3A2B", light: "#A84B39", dark: "#6E2D22", contrastText: "#fff" },
        secondary: { main: "#2F6F62", contrastText: "#fff" },
        success: { main: "#4E7A3E", light: "#6E9658" },
        background: { default: "#F6F1EB", paper: "#FFFCF8" },
        text: { primary: "#2D221C", secondary: "#6A5B50" },
        divider: "#E9DED3",
    },
    forestSand: {
        primary: { main: "#2E5F4F", light: "#3A7562", dark: "#21463A", contrastText: "#fff" },
        secondary: { main: "#BA7A36", contrastText: "#fff" },
        success: { main: "#3F7A43", light: "#5C9A63" },
        background: { default: "#F2EFE7", paper: "#FCFAF5" },
        text: { primary: "#1F2924", secondary: "#5E655F" },
        divider: "#D8D2C4",
    },
    charcoalAmber: {
        primary: { main: "#3A3A3A", light: "#505050", dark: "#262626", contrastText: "#fff" },
        secondary: { main: "#C06A2C", contrastText: "#fff" },
        success: { main: "#4B7A45", light: "#679D63" },
        background: { default: "#EEEAE4", paper: "#FBF8F3" },
        text: { primary: "#1E1B18", secondary: "#61574F" },
        divider: "#D9D1C7",
    },
    coralOlive: {
        primary: { main: "#B44B3A", light: "#CB614D", dark: "#8E3A2E", contrastText: "#fff" },
        secondary: { main: "#5E6D3C", contrastText: "#fff" },
        success: { main: "#4E7D4A", light: "#6B9B65" },
        background: { default: "#F7EFE8", paper: "#FFFCF7" },
        text: { primary: "#31221D", secondary: "#6E5D53" },
        divider: "#E8D9CD",
    },
    monochromeSlate: {
        primary: { main: "#2F2F2F", light: "#4A4A4A", dark: "#121212", contrastText: "#FFFFFF" },
        secondary: { main: "#6E6E6E", contrastText: "#FFFFFF" },
        success: { main: "#5D5D5D", light: "#7C7C7C" },
        background: { default: "#EDEDED", paper: "#FFFFFF" },
        text: { primary: "#121212", secondary: "#4F4F4F" },
        divider: "#D0D0D0",
    },
    midnightPurple: {
        primary: { main: "#4A1A6B", light: "#6B2E99", dark: "#2E0F44", contrastText: "#FFFFFF" },
        secondary: { main: "#B8860B", contrastText: "#FFFFFF" },
        success: { main: "#3A7A4A", light: "#56A066" },
        background: { default: "#F2EDF7", paper: "#FBF8FE" },
        text: { primary: "#1A0A2E", secondary: "#5E4A72" },
        divider: "#DDD0EA",
    },
    oceanTeal: {
        primary: { main: "#1A6B6B", light: "#2A8A8A", dark: "#0D4444", contrastText: "#FFFFFF" },
        secondary: { main: "#D4694A", contrastText: "#FFFFFF" },
        success: { main: "#3A7A55", light: "#569970" },
        background: { default: "#E8F4F4", paper: "#F5FAFA" },
        text: { primary: "#0D2E2E", secondary: "#4A6A6A" },
        divider: "#C4DEDE",
    },
    rosewoodGold: {
        primary: { main: "#7B2D3E", light: "#9A3A4F", dark: "#5C2030", contrastText: "#FFFFFF" },
        secondary: { main: "#C4943A", contrastText: "#FFFFFF" },
        success: { main: "#4A7A44", light: "#679960" },
        background: { default: "#F7EEEE", paper: "#FFF8F8" },
        text: { primary: "#2E1018", secondary: "#6A4A50" },
        divider: "#EAD5D8",
    },
    slateIndigo: {
        primary: { main: "#3D4A7A", light: "#5260A0", dark: "#2A3460", contrastText: "#FFFFFF" },
        secondary: { main: "#C07830", contrastText: "#FFFFFF" },
        success: { main: "#447A50", light: "#609968" },
        background: { default: "#ECEEF5", paper: "#F8F9FD" },
        text: { primary: "#1A1E30", secondary: "#505A7A" },
        divider: "#D0D4E8",
    },
    mintChocolate: {
        primary: { main: "#4A2E20", light: "#6A4030", dark: "#2E1A10", contrastText: "#FFFFFF" },
        secondary: { main: "#2E8A6A", contrastText: "#FFFFFF" },
        success: { main: "#3A7A5A", light: "#569978" },
        background: { default: "#F0EDE8", paper: "#FBF9F7" },
        text: { primary: "#1E100A", secondary: "#5E4A3A" },
        divider: "#DDD5CC",
    },
    blushBerry: {
        primary: { main: "#C43D7A", light: "#DB5C95", dark: "#9B2E61", contrastText: "#FFFFFF" },
        secondary: { main: "#7A3EC4", contrastText: "#FFFFFF" },
        success: { main: "#3E8A6E", light: "#5AA98A" },
        background: { default: "#FBEFF5", paper: "#FFF8FC" },
        text: { primary: "#3A1A2B", secondary: "#7A5A6B" },
        divider: "#EBCFDE",
    },
    midwestHarvest: {
        primary: { main: "#8B5A2B", light: "#A8733A", dark: "#6A4320", contrastText: "#FFFFFF" },
        secondary: { main: "#5E7A2F", contrastText: "#FFFFFF" },
        success: { main: "#4A7F44", light: "#66A45F" },
        background: { default: "#F7F2E8", paper: "#FFFDF8" },
        text: { primary: "#2F2418", secondary: "#6B5C4A" },
        divider: "#E3D7C4",
    },
    alpineMist: {
        primary: { main: "#3D6E7A", light: "#5290A0", dark: "#2B4F59", contrastText: "#FFFFFF" },
        secondary: { main: "#7A5C3D", contrastText: "#FFFFFF" },
        success: { main: "#3F7A5C", light: "#5A9A78" },
        background: { default: "#ECF3F5", paper: "#F8FCFD" },
        text: { primary: "#162A30", secondary: "#4E6770" },
        divider: "#CCDBDF",
    },
    sunsetMesa: {
        primary: { main: "#C45A3D", light: "#DB7454", dark: "#9B442D", contrastText: "#FFFFFF" },
        secondary: { main: "#7A3F5E", contrastText: "#FFFFFF" },
        success: { main: "#4D7A46", light: "#6B9D63" },
        background: { default: "#FAEFEA", paper: "#FFF8F4" },
        text: { primary: "#341D16", secondary: "#73554A" },
        divider: "#EDD4C9",
    },
    metroSlate: {
        primary: { main: "#44515C", light: "#5E6D7A", dark: "#2F3840", contrastText: "#FFFFFF" },
        secondary: { main: "#8A6A3D", contrastText: "#FFFFFF" },
        success: { main: "#4A7A62", light: "#67A083" },
        background: { default: "#EEF1F3", paper: "#FAFBFC" },
        text: { primary: "#1A2127", secondary: "#56616B" },
        divider: "#D3DAE0",
    },
    lavenderMilk: {
        primary: { main: "#A78BCF", light: "#C2AFE0", dark: "#876AB3", contrastText: "#FFFFFF" },
        secondary: { main: "#8BB9D9", contrastText: "#FFFFFF" },
        success: { main: "#89BFA3", light: "#A6D2BA" },
        background: { default: "#F6F1FA", paper: "#FCF9FF" },
        text: { primary: "#332B42", secondary: "#6C6180" },
        divider: "#E5DBF0",
    },
    peachSorbet: {
        primary: { main: "#E59C87", light: "#F0B9A8", dark: "#CD7F67", contrastText: "#FFFFFF" },
        secondary: { main: "#A9B9E8", contrastText: "#FFFFFF" },
        success: { main: "#8FBF9B", light: "#AFD2B8" },
        background: { default: "#FFF4EF", paper: "#FFFBF8" },
        text: { primary: "#3D2A24", secondary: "#7B625A" },
        divider: "#F1DCD3",
    },
    mintCloud: {
        primary: { main: "#8FC4B8", light: "#AFD8CF", dark: "#70A89B", contrastText: "#FFFFFF" },
        secondary: { main: "#BFA3DA", contrastText: "#FFFFFF" },
        success: { main: "#7FB894", light: "#9BC9AC" },
        background: { default: "#EFF8F5", paper: "#F9FDFC" },
        text: { primary: "#213832", secondary: "#5D7870" },
        divider: "#D7EAE4",
    },
    powderSky: {
        primary: { main: "#8EB7DD", light: "#ADCDE9", dark: "#6F9DC7", contrastText: "#FFFFFF" },
        secondary: { main: "#E0A6C4", contrastText: "#FFFFFF" },
        success: { main: "#8FB9A5", light: "#ACCCBC" },
        background: { default: "#F0F6FC", paper: "#F9FCFF" },
        text: { primary: "#223345", secondary: "#5E748B" },
        divider: "#D8E5F2",
    },
    buttercreamGarden: {
        primary: { main: "#D8B987", light: "#E6CFA9", dark: "#BF9F6F", contrastText: "#FFFFFF" },
        secondary: { main: "#9ABF93", contrastText: "#FFFFFF" },
        success: { main: "#8EB78A", light: "#ADD0AA" },
        background: { default: "#FBF8EE", paper: "#FFFDF7" },
        text: { primary: "#3D3422", secondary: "#74694E" },
        divider: "#EFE6D1",
    },
};

export const ACTIVE_THEME_PRESET = "monochromeSlate";
